language: julia

os:
  - linux
#  - osx

branches:
  only:
  - master

addons:
  apt:
    update: true

julia:
#  - 1.0
  - 1.1
#  - nightly

# matrix:
#   allow_failures:
#   - julia: nightly

notifications:
  email: false

  
after_success: skip

jobs:
  include:
    - stage: "Documentation"
      julia: 1.1
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg;  Pkg.add(PackageSpec(name="DocStringExtensions", version="0.8.0")); Pkg.add("Documenter"); Pkg.update(); Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate();'
        - julia --project=docs/ docs/make.jl
      after_success: skip

